# Broadcasting

Illustration du broadcasting.

Dans ce premier cas, les deux tableaux ayant la même dimension, on fait l'opération élément par élément.

In [1]:
import numpy as np
a = np.arange(10)
a = a.reshape((2,5))
b = (np.arange(10)+5)*2
b = b.reshape((2,5))
print("a")
print(a)
print("b")
print(b)
print("a+b")
print(a+b)

a
[[0 1 2 3 4]
 [5 6 7 8 9]]
b
[[10 12 14 16 18]
 [20 22 24 26 28]]
a+b
[[10 13 16 19 22]
 [25 28 31 34 37]]


On peut vérifier les règles de broadcasting avec la fonction `np.broadcast_arrays`.

In [2]:
arrs = np.broadcast_arrays(a, b)
for arr in arrs:
    print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 12 14 16 18]
 [20 22 24 26 28]]


Ici, rien n'a changé.

## Cas de broadcasting entre un vecteur et un ndarray

Ici, les dimensions les plus à droites coincident, mais pas les précédentes, on va donc étirer le tableau `vec` pour que sa taille devienne égale à celle de `arr` 

In [3]:
vec = np.arange(4)
arr = np.arange(7*4).reshape(7,4)
print('shapes')
print(vec.shape)
print(arr.shape)
print('vec')
print(vec)
print('arr')
print(arr)
print('vec*arr')
print(vec*arr)

shapes
(4,)
(7, 4)
vec
[0 1 2 3]
arr
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
vec*arr
[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]
 [ 0 17 36 57]
 [ 0 21 44 69]
 [ 0 25 52 81]]


In [4]:
arrs = np.broadcast_arrays(vec, arr)
for arr in arrs:
    print(arr)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


## Un cas où ça ne marche pas

In [5]:
vec = np.arange(4)
arr = np.arange(7*4).reshape(4,7)

print('shapes')
print(vec.shape)
print(arr.shape)
print('vec*arr')
print(vec*arr)

shapes
(4,)
(4, 7)
vec*arr


ValueError: operands could not be broadcast together with shapes (4,) (4,7) 

La dimension la plus à droite n'est pas identique (4 pour le vecteur, 7 pour le tableau)

## Rendre compatible des tableaux pour le broadcasting

Si on cherche à faire une **autre** opération qui consiste à faire le broadcasting sur l'avant dernière dimension de `arr`, alors il faut ajouter une nouvelle dimension à droite avec `np.expand_dims` ce qui permet de faire le broadcasting sur la dernière dimension

In [6]:
vec = np.arange(4)
#On ajoute artificiellement une dimension de plus 
vec = np.expand_dims(vec,axis=-1)
#solution équivalente
#vec = vec[:, np.newaxis]
arr = np.arange(7*4).reshape(4,7)
print('shapes')
print(vec.shape)
print(arr.shape)
print('vec')
print(vec)
print('arr')
print(arr)
print('vec*arr')
print(vec*arr)

shapes
(4, 1)
(4, 7)
vec
[[0]
 [1]
 [2]
 [3]]
arr
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
vec*arr
[[ 0  0  0  0  0  0  0]
 [ 7  8  9 10 11 12 13]
 [28 30 32 34 36 38 40]
 [63 66 69 72 75 78 81]]


In [7]:
arrs = np.broadcast_arrays(vec, arr)
for arr in arrs:
    print(arr)

[[0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3]]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


## Extension « par la gauche » en cas de dimension inégales

In [8]:
a = np.arange(2*3*4).reshape((2,3,4))
b = np.arange(4)
print('shapes')
print(a.shape)
print(b.shape)
print("a")
print(a)
print("b")
print(b)
print("a+b")
print(a+b)

arrs = np.broadcast_arrays(a, b)
for arr in arrs:
    print(arr.shape)
    print(arr)
    

shapes
(2, 3, 4)
(4,)
a
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b
[0 1 2 3]
a+b
[[[ 0  2  4  6]
  [ 4  6  8 10]
  [ 8 10 12 14]]

 [[12 14 16 18]
  [16 18 20 22]
  [20 22 24 26]]]
(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[[[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]


## Un broadcasting « piégeur »

In [9]:
a = np.arange(3)
b = np.arange(3*3).reshape((3,3))
print("a")
print(a)
print("b")
print(b)

#Broadcasting "normal" « en ligne »
print("broadcasting standard en ligne")
print(a*b)
#Broadcasting "en colonne"
print("broadcasting en colonne NON STANDARD")
print(np.expand_dims(a,axis=-1)*b)



a
[0 1 2]
b
[[0 1 2]
 [3 4 5]
 [6 7 8]]
broadcasting standard en ligne
[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]
broadcasting en colonne NON STANDARD
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]]
