In [1]:
import numpy as np

# Sélection simple d'éléments

Le slicing permet de sélectionner uniquement certains éléments.

In [42]:
data = np.arange(24)
data = data.reshape((2, 3, 4))
print(data)
print("\nsélection d'un unique élémént")
print(data[1, 2, 3])
print(data[1, 2, 3].shape)

print("\nsélection d'un vecteur")
print(data[1, 2, :])
print(data[1, 2, :].shape)

print("\nsélection d'une matrice")
print(data[1, :, :])
print(data[1, :, :].shape)
print("\navec une syntaxe plus courte")
print(data[1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

sélection d'un unique élémént
23
()

sélection d'un vecteur
[20 21 22 23]
(4,)

sélection d'une matrice
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(3, 4)

avec une syntaxe plus courte
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [43]:
print("sélection avec des indices négatifs")
print(data[-1, -2, -1])

sélection avec des indices négatifs
19


# Slicing 

In [44]:
print("tous les éléments d'indice pair dans la dernière dimension")
print(data[:, :, ::2])

tous les éléments d'indice pair dans la dernière dimension
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


In [45]:
data2 = np.arange(10 * 11 * 12)
data2 = data2.reshape((10, 11, 12))

In [46]:
print("les trois premiers éléments dans la première dimension")
print(data2[:3, :, :])

les trois premiers éléments dans la première dimension
[[[  0   1   2   3   4   5   6   7   8   9  10  11]
  [ 12  13  14  15  16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31  32  33  34  35]
  [ 36  37  38  39  40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79  80  81  82  83]
  [ 84  85  86  87  88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103 104 105 106 107]
  [108 109 110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129 130 131]]

 [[132 133 134 135 136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151 152 153 154 155]
  [156 157 158 159 160 161 162 163 164 165 166 167]
  [168 169 170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199 200 201 202 203]
  [204 205 206 207 208 209 210 211 212 213 214 215]
  [216 

In [47]:
print(
    "dans les deux premiers plan du cube, toutes les trois lignes selon la deuxième dimension"
)
print(data2[:, ::3, 0])
print(data2[:, ::3, 0:2].shape)

dans les deux premiers plan du cube, toutes les trois lignes selon la deuxième dimension
[[   0   36   72  108]
 [ 132  168  204  240]
 [ 264  300  336  372]
 [ 396  432  468  504]
 [ 528  564  600  636]
 [ 660  696  732  768]
 [ 792  828  864  900]
 [ 924  960  996 1032]
 [1056 1092 1128 1164]
 [1188 1224 1260 1296]]
(10, 4, 2)


Création d'un slice qui dépend d'une variable. On affiche tous les éléments, puis de 2 en 2, puis de 3 en 3, etc.

In [48]:
for i in range(1, data2.shape[2]):
    print("Slice ::{} dans la dernière dimension".format(i))
    print(data2[0, 0, slice(None, None, i)])

    # print("Slice équivalent ::i")
    # print(data2[0,0,slice(0,data2.shape[2],i)])

Slice ::1 dans la dernière dimension
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Slice ::2 dans la dernière dimension
[ 0  2  4  6  8 10]
Slice ::3 dans la dernière dimension
[0 3 6 9]
Slice ::4 dans la dernière dimension
[0 4 8]
Slice ::5 dans la dernière dimension
[ 0  5 10]
Slice ::6 dans la dernière dimension
[0 6]
Slice ::7 dans la dernière dimension
[0 7]
Slice ::8 dans la dernière dimension
[0 8]
Slice ::9 dans la dernière dimension
[0 9]
Slice ::10 dans la dernière dimension
[ 0 10]
Slice ::11 dans la dernière dimension
[ 0 11]


# Sélection conditionnelle d'éléments 
Pour imprimer tous les éléments du tableau multiples de 2 ou 5 et inférieurs à 500

In [49]:
print(data2[((data2 % 2 == 0) | (data2 % 5 == 0)) & (data2 < 500)])

[  0   2   4   5   6   8  10  12  14  15  16  18  20  22  24  25  26  28
  30  32  34  35  36  38  40  42  44  45  46  48  50  52  54  55  56  58
  60  62  64  65  66  68  70  72  74  75  76  78  80  82  84  85  86  88
  90  92  94  95  96  98 100 102 104 105 106 108 110 112 114 115 116 118
 120 122 124 125 126 128 130 132 134 135 136 138 140 142 144 145 146 148
 150 152 154 155 156 158 160 162 164 165 166 168 170 172 174 175 176 178
 180 182 184 185 186 188 190 192 194 195 196 198 200 202 204 205 206 208
 210 212 214 215 216 218 220 222 224 225 226 228 230 232 234 235 236 238
 240 242 244 245 246 248 250 252 254 255 256 258 260 262 264 265 266 268
 270 272 274 275 276 278 280 282 284 285 286 288 290 292 294 295 296 298
 300 302 304 305 306 308 310 312 314 315 316 318 320 322 324 325 326 328
 330 332 334 335 336 338 340 342 344 345 346 348 350 352 354 355 356 358
 360 362 364 365 366 368 370 372 374 375 376 378 380 382 384 385 386 388
 390 392 394 395 396 398 400 402 404 405 406 408 41