# Création de nombres aléatoires

En intialisant le générateur de nombre aléatoire, en fournissant un `seed` on initialise également la séquence des nombres alétoires qui seront tirés.

In [4]:
import numpy as np
rng = np.random.default_rng(25)

On va par exemple tirer dix séquences de dix entiers compris entre 0 (inclu) et 250 (exclu). Chaque tirage est bien aléatoire.

In [7]:
for i in range(10):
    print(rng.integers(0,250,10))

[ 61  20  96 234   4 118 142  55 211 175]
[187 223   4  21   7 102 118  82 196 224]
[ 43  44 211  68 162  20 138 153 246  51]
[134 168   2  61 206 209 109 177 235 232]
[ 93 106  80  40 244 236  89 160 141 227]
[199 124  20 192   0 123  37  86  98 185]
[230  60  61  20  64 113   7   2 188   5]
[240 179 183 124 107  37  80 154 205 111]
[166  65  15  75 190 194  63  71  24  17]
[ 42 233  72  70  67 138 139 109 150 227]


Mais si on réinitialise le générateur de nombre aléatoire avec le même seed, on abtiendra les mêmes séquences de nombre aléatoire. Cela peut-être très utile si jamais on teste un programme pour avoir des résultats comparables. Mais est au contraire gênant dans tous les autres cas : les séries de nombre aléatoire tirées avec le même seed étant intégralement corrélées !

In [8]:
rng2 = np.random.default_rng(25)
for i in range(10):
    print(rng2.integers(0,250,10))

[126  40 213   0  57  54 135  92  39   0]
[149  48  64 247 136 196 170  30  50  56]
[ 23 191   6 229  74  88  38 196 106  36]
[172 135 113 149 179 197 105  69 191 103]
[ 73  94 135  34  71 168 223 139 135 126]
[ 73 156 167 151  40  18  55  74 120 100]
[214  47  67 180  80 168 151 191 177   4]
[  3  24 230  61 131 135  91  19  16 231]
[146   7  79 158 145 190 118 146   6  96]
[205 215 155  73 176  46 175 137 211  30]
