**Pour tout l'exercice, il n'y a besoin d'*AUCUNE* boucle for**.

# Slicing, broadcasting et opérations sur des axes

exercice tiré du module ONP années < 2023 et adapté

Le fichier `exo4-WATER-pos-1.xyz` contenu dans l'archive `exo4-WATER.zip` correspond au résultat d'une simulation numérique correspondant à la simulation d'une boîte contenant 64 molécules d'eau sur 10 000 pas de temps espacés de 0,5 femtosecondes. La simulation concerne donc $64\times 3 =192$ atomes, dans une boîte cubique de 12,42 Å de côté en contact avec un thermostat. 

Une représentation visuelle du système est disponible à l'adresse suivante :
https://www.youtube.com/shorts/8xod-O0NwNY

Le format obtenu correspond au fait de donner pour chaque pas de temps :
* le nombre d'atomes sur une ligne
* une ligne de commentaires
* puis pour chaque atome : une ligne avec le symbole chimique de l'élément suivi de ses coordonnées $(x,y,z)$ *en Angström*

0. Avant de se jeter dans la bataille : utiliser la commande `more` sur le fichier `exo4-WATER-pos-1.xyz` pour voir la structure du fichier de départ. **Faire attention à la taille du fichier : il est trop gros (120 Mo !!) pour être lu directement par gedit ou un éditeur de texte avec interface graphique**


1. Pour une phase de test, il est fortement déconseillé de travailler sur le jeu de données complet : les tests vont être inutilement longs. On va donc ici commencer par se ramener à un fichier plus modeste avec la commande `head -n 1940 exo4-WATER-pos-1.xyz > testFile.xyz` qui va créer un fichier contenant uniquement les 10 premiers pas de temps.

2. À l'aide de la fonction `extract_data` du module `numpy_MD_utils.py` (disponible sur le dépôt github) importer les données de `testFile.xyz` sous forme de numpy array. *Ne pas hésiter à aller voir le fichier `numpy_MD_utils.py` pour voir comment utiliser la fonction*

Le tableau résultant sera à 4 dimensions :
* la première dimension sera pour chaque pas de temps
* la deuxième dimension sera pour indiquer chaque molécule d'eau
* la troisième dimension sera pour indiquer les atomes de la molécule (O,H,H)
* la quatrième dimension indiquer la coordonnée x, y ou z.

ainsi :
si `data` est le tableau, alors `data[789,13,0,2]` correspondra (lire les indices de droite à gauche) à la coordonnée z (indice 2) de l'atome d'oxygène (indice 0), de la quatorzième molécule d'eau (indice 13), au 790ième pas de temps (indice 789).


3. Regarder le shape du tableau extrait. *Il est recommandé de noter quelque part la correspondance entre dimension, grandeur physique, et le shape final pour faciliter la suite de l'exercice*
Résultat attendu :
```
shape : (10, 64, 3, 3)
```

4. Afficher les coordonnées du premier atome d'hydrogène de la deuxième molécule d'eau au deuxième pas de temps.
Les résultats doivent correspondre aux coordonnées indiquées à la ligne suivante dans le fichier de départ :
```
  H        -3.3415222496        0.8258629565        4.1545571170
```

5. Afficher la trajectoire de l'atome d'oxygène de la première molécule d'eau.
résultat attendu (en angström) :
```
[[ 3.85858738 -4.75331752  5.50919748]
 [ 3.86207789 -4.75647898  5.50987972]
 [ 3.86670402 -4.76021707  5.51020989]
 [ 3.87165408 -4.76422854  5.51167051]
 [ 3.87814674 -4.76788065  5.51245274]
 [ 3.88368732 -4.77156524  5.51394204]
 [ 3.88807613 -4.77544192  5.51568638]
 [ 3.89273159 -4.77678148  5.51657667]
 [ 3.89688626 -4.77724275  5.51936164]
 [ 3.90072985 -4.7777787   5.52115613]]
```

6. À l'aide la fonction `np.gradient` ( https://numpy.org/doc/stable/reference/generated/numpy.gradient.html ) : calculer la vitesse (en m/s) de chaque atome. *Utiliser l'option edge_order = 2 et ne calculer que la dérivée temporelle qui est la seule à avoir du sens.*  
résultat attendu pour l'atome d'oxygène de la première molécule d'eau : 
```
[[ 584.53991 -574.62943  171.65707]
 [ 811.66397 -689.95485  101.24125]
 [ 957.61961 -774.95612  179.07878]
 [1144.27258 -766.35776  224.28546]
 [1203.32347 -733.67012  227.15323]
 [ 992.93892 -756.12735  323.36409]
 [ 904.4278  -521.62392  263.46327]
 [ 881.01316 -180.0825   367.52526]
 [ 799.82575  -99.72119  457.94512]
 [ 737.61013 -114.65865  259.85056]]
```

7. Calculer l'énergie cinétique de chaque atome à l'aide de la fonction `np.sum` (et éventuellement de la fonction `np.linalg.norm` )
* On prendra comme masse molaires : 16 g/mol pour l'oxygène et 1 g/mol pour l'hydrogène
* Utiliser la librairie `scipy` et plus particulièrement `scipy.constants` pour accéder à la valeur de la constante d'Avogadro ou toute autre constante physique https://docs.scipy.org/doc/scipy/reference/constants.html

résultat attendu pour l'atome d'oxygène de la première molécule d'eau (en joule) :
```
[9.31697967e-21 1.52116788e-20 2.05861879e-20 2.58641304e-20
 2.70715400e-20 2.20814580e-20 1.54030814e-20 1.25362558e-20
 1.14162629e-20 8.29920984e-21]
```

8. À l'aide de la fonction `np.sum` : calculer la position du barycentre de chaque molécule d'eau $\mathbf{r}_{b,i} (t) = \dfrac{1}{\displaystyle\sum_{j=O,H,H} m_j}\displaystyle\sum_{j=O,H,H} m_j r_{j,i}$ où $j$ indique l'atome considéré et $i$ indique la molécule considérée ($i=0..63$). Recommencer avec la fonction `np.average`.

https://numpy.org/doc/stable/reference/generated/numpy.average.html

https://numpy.org/doc/stable/reference/generated/numpy.sum.html

résultat attendu pour le barycentre de la première molécule d'eau (en m)
```
[[ 3.83572787e-10 -4.77373429e-10  5.55890074e-10]
 [ 3.83891259e-10 -4.77672251e-10  5.55896508e-10]
 [ 3.84284552e-10 -4.78002300e-10  5.55907874e-10]
 [ 3.84722315e-10 -4.78288804e-10  5.56035633e-10]
 [ 3.85272551e-10 -4.78530403e-10  5.56119206e-10]
 [ 3.85757044e-10 -4.78809546e-10  5.56251688e-10]
 [ 3.86161465e-10 -4.79095799e-10  5.56385251e-10]
 [ 3.86638120e-10 -4.79233971e-10  5.56484026e-10]
 [ 3.87102070e-10 -4.79354019e-10  5.56796340e-10]
 [ 3.87527274e-10 -4.79472438e-10  5.57060592e-10]]
```

9. Calculer la valeur de l'énergie cinétique totale du système :
$$E_c = \dfrac{1}{2}\sum_\text{molécules}\sum_{i=\text{O,H,H}}m_i v^2$$
Puis calculer sa moyenne temporelle $\langle E_c \rangle_t$ ainsi que l'écart-type réduit correspondant :
$$\sigma_{E_c} = \sqrt{\dfrac{1}{N-1}\sum_t (E_c(t)-\langle E_c \rangle_t)^2}$$
où N est le nombre de pas de temps considérés.

En déduire la valeur de la température grâce au théorème d'équipartition de l'énergie qui donne :
$$\langle E_c\rangle_{atomes,temps} = \dfrac{3}{2}k_B T$$
où l'énergie cinétique est l'énergie cinétique moyenne calculée **par atome** (on myenne donc temporellement ainsi que pour chaque atome)

Indication : Utiliser `np.average` ou `np.mean` (https://numpy.org/doc/stable/reference/generated/numpy.mean.html) et `np.std` (https://numpy.org/doc/stable/reference/generated/numpy.std.html)

résultat attendu : 

moyenne temporelle de E_c : 1.228e-18 J, écart-type réduit : 1.061e-19 J

Température : 308.823 K

10. Pour chaque molécule, calculer la position de la **moyenne temporelle** du barycentre avec `np.mean`  ou `np.average` : $\mathbf{r}_{mtb,i} = \langle \mathbf{r}_{b,i} (t) \rangle _t$ ($i = 0..63$). Calculer ensuite la position de chaque atome par rapport à cette position $\mathbf{r}_{red}(t) = \mathbf{r}(t)-\mathbf{r}_{mtb,i}$.

Indication : ré-utiliser les résultats de la question 8, faire attention aux opérations de broadcasting, la fonction `np.expand_dims` peut servir dans ce but.

résultat attendu pour l'atome d'oxygène de la première molécule d'eau (en angström) :
```
[[ 0.00365794  0.03251544 -0.05362972]
 [ 0.00714845  0.02935398 -0.05294747]
 [ 0.01177458  0.02561589 -0.0526173 ]
 [ 0.01672465  0.02160442 -0.05115668]
 [ 0.02321731  0.01795231 -0.05037445]
 [ 0.02875788  0.01426771 -0.04888515]
 [ 0.03314669  0.01039104 -0.04714081]
 [ 0.03780216  0.00905148 -0.04625052]
 [ 0.04195683  0.00859021 -0.04346555]
 [ 0.04580042  0.00805426 -0.04167107]]
 ```
