In [1]:
import numpy as np

# Sélection simple d'éléments

Le slicing permet de sélectionner uniquement certains éléments.

In [2]:
data = np.arange(24)
data = data.reshape((2, 3, 4))
print(data)
print("\nsélection d'un unique élémént")
print(data[1, 2, 3])
print(data[1, 2, 3].shape)

print("\nsélection d'un vecteur")
print(data[1, 2, :])
print(data[1, 2, :].shape)

print("\nsélection d'une matrice")
print(data[1, :, :])
print(data[1, :, :].shape)
print("\navec une syntaxe plus courte")
print(data[1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

sélection d'un unique élémént
23
()

sélection d'un vecteur
[20 21 22 23]
(4,)

sélection d'une matrice
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(3, 4)

avec une syntaxe plus courte
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [3]:
print("sélection avec des indices négatifs")
print(data[-1, -2, -1])

sélection avec des indices négatifs
19


# Slicing 

In [4]:
print("tous les éléments d'indice pair dans la dernière dimension")
print(data[:, :, ::2])

tous les éléments d'indice pair dans la dernière dimension
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


In [5]:
data2 = np.arange(10 * 11 * 12)
data2 = data2.reshape((10, 11, 12))

In [6]:
print("les trois premiers éléments dans la première dimension")
print(data2[:3, :, :])

les trois premiers éléments dans la première dimension
[[[  0   1   2   3   4   5   6   7   8   9  10  11]
  [ 12  13  14  15  16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31  32  33  34  35]
  [ 36  37  38  39  40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79  80  81  82  83]
  [ 84  85  86  87  88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103 104 105 106 107]
  [108 109 110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129 130 131]]

 [[132 133 134 135 136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151 152 153 154 155]
  [156 157 158 159 160 161 162 163 164 165 166 167]
  [168 169 170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199 200 201 202 203]
  [204 205 206 207 208 209 210 211 212 213 214 215]
  [216 

In [7]:
print(
    "dans les deux premiers plan du cube, toutes les trois lignes selon la deuxième dimension"
)
print(data2[:, ::3, 0])
print(data2[:, ::3, 0:2].shape)

dans les deux premiers plan du cube, toutes les trois lignes selon la deuxième dimension
[[   0   36   72  108]
 [ 132  168  204  240]
 [ 264  300  336  372]
 [ 396  432  468  504]
 [ 528  564  600  636]
 [ 660  696  732  768]
 [ 792  828  864  900]
 [ 924  960  996 1032]
 [1056 1092 1128 1164]
 [1188 1224 1260 1296]]
(10, 4, 2)


Création d'un slice qui dépend d'une variable. On affiche tous les éléments, puis de 2 en 2, puis de 3 en 3, etc.

In [8]:
for i in range(1, data2.shape[2]):
    print("Slice ::{} dans la dernière dimension".format(i))
    print(data2[0, 0, slice(None, None, i)])

    # print("Slice équivalent ::i")
    # print(data2[0,0,slice(0,data2.shape[2],i)])

Slice ::1 dans la dernière dimension
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Slice ::2 dans la dernière dimension
[ 0  2  4  6  8 10]
Slice ::3 dans la dernière dimension
[0 3 6 9]
Slice ::4 dans la dernière dimension
[0 4 8]
Slice ::5 dans la dernière dimension
[ 0  5 10]
Slice ::6 dans la dernière dimension
[0 6]
Slice ::7 dans la dernière dimension
[0 7]
Slice ::8 dans la dernière dimension
[0 8]
Slice ::9 dans la dernière dimension
[0 9]
Slice ::10 dans la dernière dimension
[ 0 10]
Slice ::11 dans la dernière dimension
[ 0 11]


# Sélection conditionnelle d'éléments 
Pour imprimer tous les éléments du tableau multiples de 2 ou 5 et inférieurs à 500. L'opérateur `|` correspond à un "OU" et "&" correspond à un "ET". Il faut bien faire attention à l'ordre des opérateurs et faire attention aux parenthèses. Si on fait du masking, le tableau retourné est toujours unidimensionnel.

In [14]:
#Création d'un mask : c'est un tableau qui contient soit True pour les éléments qui vérifient la condition, soit False pour les éléments qui ne vérifient pas la condition.
mask = data2 > 1000
#On affiche tous les éléments pour lesquels mask vaut "True"
print(data2[mask])
#Il est par exemple maintenant possible de les modifier spécifiquement 
#Maintenant, on va soustraire 1000 à tous les éléments qui étaient 
data2[mask] = data2[mask]-1000
print(data2[mask])

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042
 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056
 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070
 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084
 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098
 1099 1100 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112
 1113 1114 1115 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126
 1127 1128 1129 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140
 1141 1142 1143 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154
 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1168
 1169 1170 1171 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181 1182
 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196
 1197 

In [10]:
print(data2[((data2 % 2 == 0) | (data2 % 5 == 0)) & (data2 < 500)])

[  0   2   4   5   6   8  10  12  14  15  16  18  20  22  24  25  26  28
  30  32  34  35  36  38  40  42  44  45  46  48  50  52  54  55  56  58
  60  62  64  65  66  68  70  72  74  75  76  78  80  82  84  85  86  88
  90  92  94  95  96  98 100 102 104 105 106 108 110 112 114 115 116 118
 120 122 124 125 126 128 130 132 134 135 136 138 140 142 144 145 146 148
 150 152 154 155 156 158 160 162 164 165 166 168 170 172 174 175 176 178
 180 182 184 185 186 188 190 192 194 195 196 198 200 202 204 205 206 208
 210 212 214 215 216 218 220 222 224 225 226 228 230 232 234 235 236 238
 240 242 244 245 246 248 250 252 254 255 256 258 260 262 264 265 266 268
 270 272 274 275 276 278 280 282 284 285 286 288 290 292 294 295 296 298
 300 302 304 305 306 308 310 312 314 315 316 318 320 322 324 325 326 328
 330 332 334 335 336 338 340 342 344 345 346 348 350 352 354 355 356 358
 360 362 364 365 366 368 370 372 374 375 376 378 380 382 384 385 386 388
 390 392 394 395 396 398 400 402 404 405 406 408 41