# Création de nombres aléatoires

En intialisant le générateur de nombre aléatoire, en fournissant un `seed` on initialise également la séquence des nombres alétoires qui seront tirés.

In [1]:
import numpy as np

rng = np.random.default_rng(25)

On va par exemple tirer dix séquences de dix entiers compris entre 0 (inclu) et 250 (exclu). Chaque tirage est bien aléatoire.

In [2]:
for i in range(10):
    print(rng.integers(0, 250, 10))

[126  40 213   0  57  54 135  92  39   0]
[149  48  64 247 136 196 170  30  50  56]
[ 23 191   6 229  74  88  38 196 106  36]
[172 135 113 149 179 197 105  69 191 103]
[ 73  94 135  34  71 168 223 139 135 126]
[ 73 156 167 151  40  18  55  74 120 100]
[214  47  67 180  80 168 151 191 177   4]
[  3  24 230  61 131 135  91  19  16 231]
[146   7  79 158 145 190 118 146   6  96]
[205 215 155  73 176  46 175 137 211  30]


Mais si on réinitialise le générateur de nombre aléatoire avec le même seed, on abtiendra les mêmes séquences de nombre aléatoire. Cela peut-être très utile si jamais on teste un programme pour avoir des résultats comparables. Mais est au contraire gênant dans tous les autres cas : les séries de nombre aléatoire tirées avec le même seed étant intégralement corrélées !

In [3]:
rng2 = np.random.default_rng(25)
for i in range(10):
    print(rng2.integers(0, 250, 10))

[126  40 213   0  57  54 135  92  39   0]
[149  48  64 247 136 196 170  30  50  56]
[ 23 191   6 229  74  88  38 196 106  36]
[172 135 113 149 179 197 105  69 191 103]
[ 73  94 135  34  71 168 223 139 135 126]
[ 73 156 167 151  40  18  55  74 120 100]
[214  47  67 180  80 168 151 191 177   4]
[  3  24 230  61 131 135  91  19  16 231]
[146   7  79 158 145 190 118 146   6  96]
[205 215 155  73 176  46 175 137 211  30]
